[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
extend-select = ["I", "W"]
ignore = ["D100", "D101", "D102", "D103", "E402", "E741", "F811", "F821"]
line-length = 79
show-source = true
show-fixes = true

[tool.ruff.isort]
known-first-party = ["sanic"]
known-third-party = ["pytest"]
lines-after-imports = 2
lines-between-types = 1

[tool.black]
line-length = 79

[tool.isort]
atomic = true
default_section = "THIRDPARTY"
include_trailing_comma = true
known_first_party = "sanic"
known_third_party = "pytest"
line_length = 79
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
profile = "black"

[[tool.mypy.overrides]]
module = [
    "httptools.*",
    "trustme.*",
    "sanic_routing.*",
    "aioquic.*",
    "html5tagger.*",
    "tracerite.*",
]
ignore_missing_imports = true
